# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/live/rankdb/v1.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'bilibili/live/rankdb/v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bilibili.live.component.common_model import user_dagw_pb2 as bilibili_dot_live_dot_component_dot_common__model_dot_user__dagw__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62ilibili/live/rankdb/v1.proto\x12\x17\x62ilibili.live.rankdb.v1\x1a\x34\x62ilibili/live/component/common_model/user_dagw.proto\"\x9d\x03\n\x11GoldRankBroadcast\x12\x11\n\trank_type\x18\x01 \x01(\t\x12M\n\x04list\x18\x02 \x03(\x0b\x32?.bilibili.live.rankdb.v1.GoldRankBroadcast.GoldRankBrodcastItem\x12T\n\x0bonline_list\x18\x03 \x03(\x0b\x32?.bilibili.live.rankdb.v1.GoldRankBroadcast.GoldRankBrodcastItem\x1a\xcf\x01\n\x14GoldRankBrodcastItem\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0c\n\x04\x66\x61\x63\x65\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\t\x12\r\n\x05uname\x18\x04 \x01(\t\x12\x0c\n\x04rank\x18\x05 \x01(\x03\x12\x13\n\x0bguard_level\x18\x06 \x01(\x03\x12\x12\n\nis_mystery\x18\x07 \x01(\x08\x12G\n\x05uinfo\x18\x08 \x01(\x0b\x32\x38.bilibili.live.component.common_model.user_dagw.UserInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.live.rankdb.v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOLDRANKBROADCAST']._serialized_start=113
  _globals['_GOLDRANKBROADCAST']._serialized_end=526
  _globals['_GOLDRANKBROADCAST_GOLDRANKBRODCASTITEM']._serialized_start=319
  _globals['_GOLDRANKBROADCAST_GOLDRANKBRODCASTITEM']._serialized_end=526
# @@protoc_insertion_point(module_scope)
